GET /soudaxue/queryProvinceScore.html?messtype=jsonp&lunum=1&callback=jQuery183004699848380735716_1530334780307&provinceforschool=&schooltype=&page=1&size=10&keyWord=&schoolproperty=&schoolflag=&province=&fstype=&zhaoshengpici=&fsyear=&_=1530334780559
Cookie: tool_ipprovince=42; tool_ipuse=202.114.121.194; tool_iparea=4
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Accept-Language: zh-Hans-CN,zh-Hans;q=0.8,en-US;q=0.5,en;q=0.3
Host: data-gkcx.eol.cn